<?php

/**
 * This file is part of the authbucket/oauth2-php package.
 *
 * (c) Wong Hoi Sing Edison <hswong3i@pantarei-design.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Perseids\Entity;

use AuthBucket\OAuth2\Model\ClientManagerInterface;
use Perseids\Entity\AbstractEntityRepository;

/**
 * ClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientRepository extends AbstractEntityRepository implements ClientManagerInterface
{
    /**
    * Count users that match the given criteria.
    *
    * @param array $criteria
    * @return int The number of users that match the criteria.
    */
    public function findCount(array $criteria = array())
    {
        return $this->createQueryBuilder('id')
            ->select('COUNT(id)')
            ->getQuery()
            ->getSingleScalarResult()
        ;
    }
}
